[package]
name = "horsenuggets/dotenv-luau"
description = "A dotenv parser implemented in Luau."
version = "0.0.1"
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/horsenuggets/dotenv-luau"
